version: "3.0"

services:
  prometheus:
    image: "prom/prometheus:latest"
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle --web.enable-admin-api
    environment:
      - LOGSPOUT=ignore
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: host
    extra_hosts:
      - "host.docker.internal:127.0.0.1"
